//CONSTANTES UTILIZADAS NO CODIGO
var CONSTS = {};
CONSTS.EVAL_BY_CATEGORIES = 1;
CONSTS.EVAL_BY_QUESTIONS = 2;
CONSTS.FIXED_ORDER = 'fixed_order';
CONSTS.DIF_BALANCE = 'dif_balance';

module.exports = CONSTS;